name: Notifier

on:
  schedule:
    - cron: "5 * * * *"
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9    
      - name: Send GroupMe notification
        env:
          GROUPME_BOT: ${{ secrets.GROUPME_BOT }}
          GROUPME_KEY: ${{ secrets.GROUPME_KEY }}
          GCP_SA: ${{ secrets.GCP_SA }}
        run: |
          ls
          python -m ufcevents
